// Auto-generated by garmin_sync.py on 2026-07-17
// Do not edit manually — re-run garmin_sync.py to refresh
window.GARMIN = {
  "date": "2026-07-17",
  "metrics": {
    "sleep_score": 80,
    "sleep_hours": 6.8,
    "hrv_status": "BALANCED",
    "hrv_last_night": 60,
    "hrv_baseline_low": 50,
    "hrv_baseline_high": 67,
    "body_battery": 80,
    "resting_hr": 54,
    "avg_stress": 21
  },
  "readiness": {
    "score": 84,
    "summary": "Readiness 84/100 — recovery base 84 (body battery/sleep/HRV) − weights 0 − golf 0. Runs judged by HR, not Garmin's label. On-device, no Claude.",
    "sessions": {
      "VO2 Max": {
        "status": "good",
        "reason": "Recovery 84/100"
      },
      "Tempo": {
        "status": "good",
        "reason": "Recovery 84/100"
      },
      "Long Run": {
        "status": "good",
        "reason": "Recovery 84/100"
      },
      "Zone 2": {
        "status": "good",
        "reason": "Easy aerobic by feel — restorative; golf/weights don't block it."
      },
      "Weights": {
        "status": "good",
        "reason": "recovery 84/100"
      },
      "Mobility": {
        "status": "good",
        "reason": "Always beneficial — especially after golf or a hard day."
      },
      "Golf": {
        "status": "good",
        "reason": "Aerobic volume + back/leg load — fine unless legs are cooked."
      }
    },
    "vo2max": {
      "value": 46.8,
      "date": "2026-07-14"
    }
  }
};
