// Auto-generated by garmin_sync.py on 2026-07-14
// Do not edit manually — re-run garmin_sync.py to refresh
window.GARMIN = {
  "date": "2026-07-14",
  "metrics": {
    "sleep_score": 83,
    "sleep_hours": 7.6,
    "hrv_status": "BALANCED",
    "hrv_last_night": 53,
    "hrv_baseline_low": 50,
    "hrv_baseline_high": 66,
    "body_battery": 73,
    "resting_hr": 52,
    "avg_stress": 21
  },
  "readiness": {
    "score": 81,
    "summary": "Readiness 81/100 — recovery base 81 (body battery/sleep/HRV) − weights 0 − golf 0. Runs judged by HR, not Garmin's label. On-device, no Claude.",
    "sessions": {
      "VO2 Max": {
        "status": "caution",
        "reason": "Hard session (by hr) in last 24h"
      },
      "Tempo": {
        "status": "caution",
        "reason": "Hard session (by hr) in last 24h"
      },
      "Long Run": {
        "status": "caution",
        "reason": "Hard session (by hr) in last 24h"
      },
      "Zone 2": {
        "status": "good",
        "reason": "Easy aerobic by feel — restorative; golf/weights don't block it."
      },
      "Weights": {
        "status": "good",
        "reason": "recovery 81/100"
      },
      "Mobility": {
        "status": "good",
        "reason": "Always beneficial — especially after golf or a hard day."
      },
      "Golf": {
        "status": "good",
        "reason": "Aerobic volume + back/leg load — fine unless legs are cooked."
      }
    },
    "vo2max": {
      "value": 47.0,
      "date": "2026-07-13"
    }
  }
};
