// Auto-generated by garmin_sync.py on 2026-09-09
// Do not edit manually — re-run garmin_sync.py to refresh
window.GARMIN = {
  "date": "2026-09-09",
  "metrics": {
    "sleep_score": 86,
    "sleep_hours": 7.7,
    "hrv_status": "BALANCED",
    "hrv_last_night": 63,
    "hrv_baseline_low": 48,
    "hrv_baseline_high": 69,
    "body_battery": 79,
    "resting_hr": 53,
    "avg_stress": 18
  },
  "readiness": {
    "score": 85,
    "summary": "Readiness 85/100 — recovery base 85 (body battery/sleep/HRV) − weights 0 − golf 0. Runs judged by HR, not Garmin's label. On-device, no Claude.",
    "sessions": {
      "VO2 Max": {
        "status": "good",
        "reason": "Recovery 85/100"
      },
      "Tempo": {
        "status": "good",
        "reason": "Recovery 85/100"
      },
      "Long Run": {
        "status": "good",
        "reason": "Recovery 85/100"
      },
      "Zone 2": {
        "status": "good",
        "reason": "Easy aerobic by feel — restorative; golf/weights don't block it."
      },
      "Weights": {
        "status": "good",
        "reason": "recovery 85/100"
      },
      "Mobility": {
        "status": "good",
        "reason": "Always beneficial — especially after golf or a hard day."
      },
      "Golf": {
        "status": "good",
        "reason": "Aerobic volume + back/leg load — fine unless legs are cooked."
      }
    },
    "vo2max": {
      "value": 45.8,
      "date": "2026-09-07"
    }
  }
};
